AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
  Exclude:
    - test/**/*
    - vendor/**/*

LineLength:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Exclude:
    - '**/metadata.rb'
HashSyntax:
  Enabled: false
